# Módulo 07, Tarefa 01

Vamos começar a mexer na nossa base de projeto? Já fizemos um exercício de montar a variável resposta, já pudemos perceber que essa atividade pode não ser trivial. Vamos agora trabalhar a base para que fique propícia ao *scikitlearn* para trabalharmos.

Lembrando, a base se chama demo01.csv, e originalmente está publicada [aqui](https://www.kaggle.com/rikdifos/credit-card-approval-prediction).

In [1]:
import pandas as pd
import numpy as np
import gdown
import requests

In [2]:
file_id = '1xRvt2wjwSXMFjPNkh6K8lryxgvmc0fy_'
url = f'https://drive.google.com/uc?id={file_id}'

#### 1) Carregue a base e avalie:

- As variáveis
- Tipos de dados de cada variável
- Quantidade de missings
- Distribuição da variável resposta (mau)

In [3]:
demo01 = pd.read_csv(url)
demo01.head(10)

,sexo,posse_de_veiculo,posse_de_imovel,qtd_filhos,tipo_renda,educacao,estado_civil,tipo_residencia,idade,tempo_emprego,possui_celular,possui_fone_comercial,possui_fone,possui_email,qt_pessoas_residencia,mau
0,M,Y,Y,0,Working,Secondary / secondary special,Married,House / apartment,58.832877,3.106849,1,0,0,0,2.0,False
1,F,N,Y,0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,52.356164,8.358904,1,0,1,1,1.0,False
2,F,N,Y,0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,52.356164,8.358904,1,0,1,1,1.0,False
3,M,Y,Y,0,Working,Higher education,Married,House / apartment,46.224658,2.106849,1,1,1,1,2.0,False
4,F,Y,N,0,Working,Incomplete higher,Married,House / apartment,29.230137,3.021918,1,0,0,0,2.0,False
5,F,Y,N,0,Working,Incomplete higher,Married,House / apartment,29.230137,3.021918,1,0,0,0,2.0,False
6,F,N,Y,0,Working,Secondary / secondary special,Married,House / apartment,27.482192,4.024658,1,0,1,0,2.0,False
7,F,N,Y,0,Working,Secondary / secondary special,Married,House / apartment,27.482192,4.024658,1,0,1,0,2.0,False
8,F,N,Y,1,Working,Secondary / secondary special,Single / not married,House / apartment,30.049315,4.438356,1,0,0,0,2.0,False
9,F,N,Y,1,Working,Secondary / secondary special,Single / not married,House / apartment,30.049315,4.438356,1,0,0,0,2.0,False

In [4]:
demo01.columns

Index(['sexo', 'posse_de_veiculo', 'posse_de_imovel', 'qtd_filhos',
       'tipo_renda', 'educacao', 'estado_civil', 'tipo_residencia', 'idade',
       'tempo_emprego', 'possui_celular', 'possui_fone_comercial',
       'possui_fone', 'possui_email', 'qt_pessoas_residencia', 'mau'],
      dtype='object')

In [5]:
demo01.dtypes

sexo                      object
posse_de_veiculo          object
posse_de_imovel           object
qtd_filhos                 int64
tipo_renda                object
educacao                  object
estado_civil              object
tipo_residencia           object
idade                    float64
tempo_emprego            float64
possui_celular             int64
possui_fone_comercial      int64
possui_fone                int64
possui_email               int64
qt_pessoas_residencia    float64
mau                         bool
dtype: object

In [6]:
demo01.isna().sum()

sexo                     0
posse_de_veiculo         0
posse_de_imovel          0
qtd_filhos               0
tipo_renda               0
educacao                 0
estado_civil             0
tipo_residencia          0
idade                    0
tempo_emprego            0
possui_celular           0
possui_fone_comercial    0
possui_fone              0
possui_email             0
qt_pessoas_residencia    0
mau                      0
dtype: int64

In [7]:
distribuicao = demo01['mau'].value_counts()
distribuicao

mau
False    16260
True       390
Name: count, dtype: int64

#### 2) Vamos montar um metadados

1. Crie um dataframe com os nomes de cada variável e o tipo de dados de cada variável.
2. Adicione uma coluna nesse *dataframe* chamada "qtd_categorias" e coloque nela o número de categorias correspondente de cada variável.
    Dica:
        1. inicie uma lista vazia
        2. faça um for ao longo dos nomes das variáveis,
        3. conte o número de categorias dessa variável
        4. acumule essa informação de 3. na lista que você criou em 1.
        5. No final, essa lista pode ser atribuída à nossa variável.

In [8]:
metadados = pd.DataFrame({'nome_variavel': demo01.columns, 'tipo_dados': demo01.dtypes})
metadados

                               nome_variavel tipo_dados
sexo                                    sexo     object
posse_de_veiculo            posse_de_veiculo     object
posse_de_imovel              posse_de_imovel     object
qtd_filhos                        qtd_filhos      int64
tipo_renda                        tipo_renda     object
educacao                            educacao     object
estado_civil                    estado_civil     object
tipo_residencia              tipo_residencia     object
idade                                  idade    float64
tempo_emprego                  tempo_emprego    float64
possui_celular                possui_celular      int64
possui_fone_comercial  possui_fone_comercial      int64
possui_fone                      possui_fone      int64
possui_email                    possui_email      int64
qt_pessoas_residencia  qt_pessoas_residencia    float64
mau                                      mau       bool

In [9]:
qtd_categorias = []

for coluna in demo01.columns:
    qtd_categorias.append(demo01[coluna].nunique())

metadados['qtd_categorias'] = qtd_categorias
metadados

                               nome_variavel tipo_dados  qtd_categorias
sexo                                    sexo     object               2
posse_de_veiculo            posse_de_veiculo     object               2
posse_de_imovel              posse_de_imovel     object               2
qtd_filhos                        qtd_filhos      int64               8
tipo_renda                        tipo_renda     object               5
educacao                            educacao     object               5
estado_civil                    estado_civil     object               5
tipo_residencia              tipo_residencia     object               6
idade                                  idade    float64            5298
tempo_emprego                  tempo_emprego    float64            3005
possui_celular                possui_celular      int64               1
possui_fone_comercial  possui_fone_comercial      int64               2
possui_fone                      possui_fone      int64               2
possui_email                    possui_email      int64               2
qt_pessoas_residencia  qt_pessoas_residencia    float64               9
mau                                      mau       bool               2

#### 3) Crie variáveis dummy para as variáveis necessárias (i.e. aquelas que são qualitativas e não estão armazenadas como {0, 1} ou {True, False}. Crie um *dataframe* apenas com as variáveis apropriadas para entrada no scikitlearn - elimine as variáveis tipo *str*, mantendo apenas suas versões *dummy*.

In [25]:
colunas_para_processar = ['posse_de_veiculo', 'posse_de_imovel', 'tipo_renda', 'educacao', 'estado_civil', 'tipo_residencia']

# Criar dummies para as colunas qualitativas
demo01_dummies = pd.get_dummies(demo01, columns=colunas_para_processar, drop_first=True)

# Exibir as primeiras linhas do novo dataframe com dummies
demo01_dummies.head()

,sexo,qtd_filhos,idade,tempo_emprego,possui_celular,possui_fone_comercial,possui_fone,possui_email,qt_pessoas_residencia,mau,...,educacao_Secondary / secondary special,estado_civil_Married,estado_civil_Separated,estado_civil_Single / not married,estado_civil_Widow,tipo_residencia_House / apartment,tipo_residencia_Municipal apartment,tipo_residencia_Office apartment,tipo_residencia_Rented apartment,tipo_residencia_With parents
0,M,0,58.832877,3.106849,1,0,0,0,2.0,False,...,True,True,False,False,False,True,False,False,False,False
1,F,0,52.356164,8.358904,1,0,1,1,1.0,False,...,True,False,False,True,False,True,False,False,False,False
2,F,0,52.356164,8.358904,1,0,1,1,1.0,False,...,True,False,False,True,False,True,False,False,False,False
3,M,0,46.224658,2.106849,1,1,1,1,2.0,False,...,False,True,False,False,False,True,False,False,False,False
4,F,0,29.230137,3.021918,1,0,0,0,2.0,False,...,False,True,False,False,False,True,False,False,False,False

#### 4) Qual variável é mais poderosa?

Considere as variáveis ```possui_email``` e ```posse_de_veiculo```. Faça uma tabela cruzada entre elas e responda qual delas te parece mais poderosa para prever a probabilidade de ```mau = 1```?

#### 5) Salve a base, pois ela será utilizada no final deste módulo.